import StyleDictionary from 'style-dictionary';

function cssVarName(token) {
	return token.path
		.filter((segment) => segment !== 'light' && segment !== 'dark')
		.join('-');
}

function escapeCSharpString(value) {
	return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"');
}

StyleDictionary.registerFormat({
	name: 'css/theme-variables',
	format: async ({ dictionary }) => {
		const light = dictionary.allTokens.filter((t) => t.path.at(-1) === 'light');
		const dark = dictionary.allTokens.filter((t) => t.path.at(-1) === 'dark');
		const themeless = dictionary.allTokens.filter(
			(t) => t.path.at(-1) !== 'light' && t.path.at(-1) !== 'dark',
		);

		const rootLines = [...themeless, ...light].map((t) => `  --${cssVarName(t)}: ${t.$value};`);
		const darkLines = dark.map((t) => `    --${cssVarName(t)}: ${t.$value};`);

		// Media-query-driven, not attribute-driven: nothing in the platform sets [data-theme]
		// yet (confirmed by search, 2026-07-12), and the actual requirement is "flip the OS/
		// browser preference and reload" — see the Theme Selection Machinery addendum, Decision 3.
		// A [data-theme] override can be layered on top later without touching this shape.
		return `:root {\n${rootLines.join('\n')}\n}\n\n@media (prefers-color-scheme: dark) {\n  :root {\n${darkLines.join('\n')}\n  }\n}\n`;
	},
});

StyleDictionary.registerFormat({
	name: 'csharp/fluent-token-seed',
	format: async ({ dictionary }) => {
		const accent = dictionary.allTokens.find((t) => t.path.join('.') === 'color.amber.700');
		const neutral = dictionary.allTokens.find((t) => t.path.join('.') === 'color.neutral.500');
		if (!accent || !neutral) {
			throw new Error('FluentTokenSeed: expected color.amber.700 and color.neutral.500 to exist in tokens/color.json');
		}
		return (
			`namespace Norse.DesignSystem;\n\n` +
			`// Generated by Style Dictionary from tokens/color.json — do not edit by hand.\n` +
			`/// <summary>Seed color values for FluentUI Blazor's DesignTokens, generated from Naglfar's color tokens.</summary>\n` +
			`public static class FluentTokenSeed\n{\n` +
			`\t/// <summary>Accent base color (color.amber.700).</summary>\n` +
			`\tpublic const string AccentBaseColor = "${escapeCSharpString(accent.$value)}";\n\n` +
			`\t/// <summary>Neutral base color (color.neutral.500).</summary>\n` +
			`\tpublic const string NeutralBaseColor = "${escapeCSharpString(neutral.$value)}";\n` +
			`}\n`
		);
	},
});

const sd = new StyleDictionary({
	source: ['tokens/**/*.json'],
	platforms: {
		css: {
			transformGroup: 'css',
			buildPath: 'dist/css/',
			files: [
				{
					destination: 'tokens.css',
					format: 'css/theme-variables',
				},
			],
		},
		cssWwwroot: {
			transformGroup: 'css',
			buildPath: 'src/DesignSystem.Tokens/wwwroot/',
			files: [
				{
					destination: 'norse-design-tokens.css',
					format: 'css/theme-variables',
				},
			],
		},
		js: {
			transformGroup: 'js',
			buildPath: 'dist/js/',
			files: [
				{
					destination: 'tokens.js',
					format: 'javascript/es6',
				},
			],
		},
		json: {
			transformGroup: 'js',
			buildPath: 'dist/json/',
			files: [
				{
					destination: 'tokens.json',
					format: 'json/nested',
				},
			],
		},
		csharp: {
			transformGroup: 'css',
			buildPath: 'dist/csharp/',
			files: [
				{
					destination: 'FluentTokenSeed.g.cs',
					format: 'csharp/fluent-token-seed',
				},
			],
		},
	},
});

await sd.buildAllPlatforms();
