import StyleDictionary from 'style-dictionary';

function cssVarName(token) {
	return token.path
		.filter((segment) => segment !== 'light' && segment !== 'dark')
		.join('-');
}

StyleDictionary.registerFormat({
	name: 'css/theme-variables',
	format: async ({ dictionary }) => {
		const light = dictionary.allTokens.filter((t) => t.path.at(-1) === 'light');
		const dark = dictionary.allTokens.filter((t) => t.path.at(-1) === 'dark');
		const themeless = dictionary.allTokens.filter(
			(t) => t.path.at(-1) !== 'light' && t.path.at(-1) !== 'dark',
		);

		const rootLines = [...themeless, ...light].map((t) => `  --${cssVarName(t)}: ${t.$value};`);
		const darkLines = dark.map((t) => `  --${cssVarName(t)}: ${t.$value};`);

		return `:root {\n${rootLines.join('\n')}\n}\n\n[data-theme="dark"] {\n${darkLines.join('\n')}\n}\n`;
	},
});

StyleDictionary.registerFormat({
	name: 'csharp/fluent-token-seed',
	format: async ({ dictionary }) => {
		const accent = dictionary.allTokens.find((t) => t.path.join('.') === 'color.amber.700');
		const neutral = dictionary.allTokens.find((t) => t.path.join('.') === 'color.neutral.500');
		if (!accent || !neutral) {
			throw new Error('FluentTokenSeed: expected color.amber.700 and color.neutral.500 to exist in tokens/color.json');
		}
		return (
			`namespace Norse.DesignSystem;\n\n` +
			`// Generated by Style Dictionary from tokens/color.json — do not edit by hand.\n` +
			`public static class FluentTokenSeed\n{\n` +
			`\tpublic const string AccentBaseColor = "${accent.$value}";\n` +
			`\tpublic const string NeutralBaseColor = "${neutral.$value}";\n` +
			`}\n`
		);
	},
});

const sd = new StyleDictionary({
	source: ['tokens/**/*.json'],
	platforms: {
		css: {
			transformGroup: 'css',
			buildPath: 'dist/css/',
			files: [
				{
					destination: 'tokens.css',
					format: 'css/theme-variables',
				},
			],
		},
		js: {
			transformGroup: 'js',
			buildPath: 'dist/js/',
			files: [
				{
					destination: 'tokens.js',
					format: 'javascript/es6',
				},
			],
		},
		json: {
			transformGroup: 'js',
			buildPath: 'dist/json/',
			files: [
				{
					destination: 'tokens.json',
					format: 'json/nested',
				},
			],
		},
		csharp: {
			transformGroup: 'css',
			buildPath: 'dist/csharp/',
			files: [
				{
					destination: 'FluentTokenSeed.g.cs',
					format: 'csharp/fluent-token-seed',
				},
			],
		},
	},
});

await sd.buildAllPlatforms();
